CREATE TABLE Countries(
   country  VARCHAR(40) NOT NULL PRIMARY KEY
  ,currency VARCHAR(6) NOT NULL
  ,rate     BIGINT  NOT NULL
);
INSERT INTO Countries(country,currency,rate) VALUES ('Afghanistan','AFN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Akrotiri and Dhekelia (UK)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Aland Islands (Finland)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Albania','ALL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Algeria','DZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('American Samoa (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Andorra','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Angola','AOA',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Anguilla (UK)','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Antigua and Barbuda','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Argentina','ARS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Armenia','AMD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Aruba (Netherlands)','AWG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ascension Island (UK)','SHP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Australia','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Austria','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Azerbaijan','AZN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bahamas','BSD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bahrain','BHD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bangladesh','BDT',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Barbados','BBD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Belarus','BYN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Belgium','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Belize','BZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Benin','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bermuda (UK)','BMD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bhutan','BTN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bolivia','BOB',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bonaire (Netherlands)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bosnia and Herzegovina','BAM',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Botswana','BWP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Brazil','BRL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('British Indian Ocean Territory (UK)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('British Virgin Islands (UK)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Brunei','BND',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Bulgaria','BGN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Burkina Faso','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Burundi','BIF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cabo Verde','CVE',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cambodia','KHR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cameroon','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Canada','CAD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Caribbean Netherlands (Netherlands)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cayman Islands (UK)','KYD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Central African Republic','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Chad','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Chatham Islands (New Zealand)','NZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Chile','CLP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('China','CNY',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Christmas Island (Australia)','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cocos (Keeling) Islands (Australia)','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Colombia','COP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Comoros','KMF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Congo, Democratic Republic of the','CDF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Congo, Republic of the','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cook Islands (New Zealand)','none',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Costa Rica','CRC',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cote d''Ivoire','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Croatia','HRK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cuba','CUP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Curacao (Netherlands)','ANG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Cyprus','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Czechia','CZK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Denmark','DKK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Djibouti','DJF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Dominica','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Dominican Republic','DOP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ecuador','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Egypt','EGP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('El Salvador','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Equatorial Guinea','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Eritrea','ERN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Estonia','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Eswatini (formerly Swaziland)','SZL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ethiopia','ETB',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Falkland Islands (UK)','FKP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Faroe Islands (Denmark)','none',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Fiji','FJD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Finland','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('France','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('French Guiana (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('French Polynesia (France)','XPF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Gabon','XAF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Gambia','GMD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Georgia','GEL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Germany','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ghana','GHS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Gibraltar (UK)','GIP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Greece','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Greenland (Denmark)','DKK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Grenada','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guadeloupe (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guam (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guatemala','GTQ',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guernsey (UK)','GGP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guinea','GNF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guinea-Bissau','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Guyana','GYD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Haiti','HTG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Honduras','HNL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Hong Kong (China)','HKD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Hungary','HUF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Iceland','ISK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('India','INR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Indonesia','IDR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('International Monetary Fund (IMF)','XDR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Iran','IRR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Iraq','IQD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ireland','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Isle of Man (UK)','IMP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Israel','ILS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Italy','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Jamaica','JMD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Japan','JPY',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Jersey (UK)','JEP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Jordan','JOD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kazakhstan','KZT',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kenya','KES',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kiribati','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kosovo','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kuwait','KWD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Kyrgyzstan','KGS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Laos','LAK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Latvia','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Lebanon','LBP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Lesotho','LSL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Liberia','LRD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Libya','LYD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Liechtenstein','CHF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Lithuania','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Luxembourg','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Macau (China)','MOP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Madagascar','MGA',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Malawi','MWK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Malaysia','MYR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Maldives','MVR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mali','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Malta','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Marshall Islands','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Martinique (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mauritania','MRU',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mauritius','MUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mayotte (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mexico','MXN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Micronesia','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Moldova','MDL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Monaco','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mongolia','MNT',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Montenegro','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Montserrat (UK)','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Morocco','MAD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Mozambique','MZN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Myanmar (formerly Burma)','MMK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Namibia','NAD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Nauru','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Nepal','NPR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Netherlands','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('New Caledonia (France)','XPF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('New Zealand','NZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Nicaragua','NIO',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Niger','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Nigeria','NGN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Niue (New Zealand)','NZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Norfolk Island (Australia)','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Northern Mariana Islands (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('North Korea','KPW',0);
INSERT INTO Countries(country,currency,rate) VALUES ('North Macedonia (formerly Macedonia)','MKD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Norway','NOK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Oman','OMR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Pakistan','PKR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Palau','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Palestine','ILS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Panama','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Papua New Guinea','PGK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Paraguay','PYG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Peru','PEN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Philippines','PHP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Pitcairn Islands (UK)','NZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Poland','PLN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Portugal','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Puerto Rico (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Qatar','QAR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Reunion (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Romania','RON',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Russia','RUB',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Rwanda','RWF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saba (Netherlands)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Barthelemy (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Helena (UK)','SHP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Kitts and Nevis','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Lucia','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Martin (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Pierre and Miquelon (France)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saint Vincent and the Grenadines','XCD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Samoa','WST',0);
INSERT INTO Countries(country,currency,rate) VALUES ('San Marino','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sao Tome and Principe','STN',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Saudi Arabia','SAR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Senegal','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Serbia','RSD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Seychelles','SCR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sierra Leone','SLL',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Singapore','SGD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sint Eustatius (Netherlands)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sint Maarten (Netherlands)','ANG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Slovakia','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Slovenia','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Solomon Islands','SBD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Somalia','SOS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('South Africa','ZAR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('South Georgia Island (UK)','GBP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('South Korea','KRW',0);
INSERT INTO Countries(country,currency,rate) VALUES ('South Sudan','SSP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Spain','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sri Lanka','LKR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sudan','SDG',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Suriname','SRD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Svalbard and Jan Mayen (Norway)','NOK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Sweden','SEK',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Switzerland','CHF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Syria','SYP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Taiwan','TWD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tajikistan','TJS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tanzania','TZS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Thailand','THB',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Timor-Leste','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Togo','XOF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tokelau (New Zealand)','NZD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tonga','TOP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Trinidad and Tobago','TTD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tristan da Cunha (UK)','GBP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tunisia','TND',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Turkey','TRY',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Turkmenistan','TMT',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Turks and Caicos Islands (UK)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Tuvalu','AUD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Uganda','UGX',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Ukraine','UAH',0);
INSERT INTO Countries(country,currency,rate) VALUES ('United Arab Emirates','AED',0);
INSERT INTO Countries(country,currency,rate) VALUES ('United Kingdom','GBP',0);
INSERT INTO Countries(country,currency,rate) VALUES ('United States of America','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Uruguay','UYU',0);
INSERT INTO Countries(country,currency,rate) VALUES ('US Virgin Islands (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Uzbekistan','UZS',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Vanuatu','VUV',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Vatican City (Holy See)','EUR',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Venezuela','VES',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Vietnam','VND',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Wake Island (USA)','USD',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Wallis and Futuna (France)','XPF',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Yemen','YER',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Zambia','ZMW',0);
INSERT INTO Countries(country,currency,rate) VALUES ('Zimbabwe','USD',0);
